balena-os/autokit-interface-sw

lib/features/power/implementations/autokit-relay/index.ts

In order for the double relay to work correctly, we must use the 0 index to turn both of them on/off at the same time.
Change-type: minor
Signed-off-by: Pedro Henrique Kopper <pedro.kopper@balena.io>

Add double relay support

---

lib/features/power/implementations/autokit-relay/index.ts

Allow for cases where the user has a relay set up with NC instead of NO - the main use of this feature is for debugging right now

allow relay to have NC configuration

---

lib/features/network/implementations/linux-device/networkManager.ts

resolves an issue where wired ethernnet sharing would fail if a connected device powered off then on again. It would not reconnect.

fix wired ethernet reconnects

---

package.json

Node 10 and 12 are already EOL, Node 14 will be EOL in April. Bumping the minimum version to 16 will help us avoid problems in the future.
Signed-off-by: Pedro Henrique Kopper <pedro.kopper@balena.io>

Bump minimum node version to 16

---

LICENSE
package-lock.json
package.json

Scoping NPM packages prevents supply chain attacks https://github.blog/2021-02-12-avoiding-npm-substitution-attacks/
Added License
and, updated the lockfile to version 2 that comes with npm v7: https://www.abrahamberg.com/blog/npm-package-json-lock-version-1-or-2/
The last commit is to be merged if everyone has started using node v16 (latest LTS)
If not, I can remove it.

Get autokit NPM package under balena scope

---

package-lock.json
package.json

This includes an etcher-sdk fix so it works with raspberrypi cm4

bump etcher-sdk to 7.4.8

---

lib/features/digitalRelay/implementations/usb-relay/index.ts
lib/flashing/index.ts

Some devices have capacitors that mean you must wait for them to discharge before re applying power to the DUT after it has flashed. This adds an env var `CAP_DELAY` to add a configurable wait.

allow for configurable delay on flasher images

---

lib/features/power/implementations/crelay/README.md
lib/features/power/implementations/crelay/index.ts
lib/features/power/index.ts

Add support for crelay supported usb relays: https://github.com/ondrej1024/crelay
This tool can be used to control the original usb relay too - technically making the AutokitRelay class redundant - but leaving it there for now for removal at a later day following in the field testing of this new implementation. 
To be used with leviathan-worker, an additional PR (pending) on that repo must be merged. 
To select this device, the env var `POWER=crelay` can be set
Change-type: patch`

add crelay implementation

---

lib/features/sd-mux/implementations/linux-gmbh/index.ts

We encountered an issue when using a host for the autokit that had multiple scsi-generic (`/dev/sg*`) devices attached. We were using `/dev/sg*` to address the mux which caused problems when multiple devices were attached. 
Added a small piece of setup that searches for the correct sg device, using the vendor name.

search for correct sg device with linuxAut mux

---

lib/flashing/devices/ iot-gate-imx8plus-d1d8.json
lib/flashing/devices/iot-gate-imx8plus.json
lib/flashing/index.ts
lib/index.ts
lib/interfaces.d.ts

add iot-gate devices

---

lib/flashing/devices/jetson-xavier.json

The Xavier AGX is flashed using the jetson-flash node app, and boots from the eMMC.

lib/flashing/devices: Add json for jetson-xavier

---

lib/flashing/index.ts

This should allow the DUT to cool off while not in use, because in rcm-boot mode the fan is not spinning.
Also, with this commit we check if the following error observed on J3010 disappears:
ECID is 
Board ID() version() sku() revision()
Chip SKU(00:00:00:D3) ramcode() fuselevel(fuselevel_production)   board_FAB()
emc_opt_disable_fuse:(0)
Error: Unrecognized module SKU
Signed-off-by: Alexandru Costache <alexandru@balena.io

flashing/index: Power off Jetson DUT on container flash failure

---

lib/flashing/devices/jetson-agx-orin-devkit-64gb.json

Even if the flasher image will be switched
to provisioning the eMMC, a flasher image
will still be used so nvme can be kept in the
json.

flashing/devices: Add Jetson AGX Orin Devkit 64GB

---

lib/features/sd-mux/implementations/linux-gmbh/index.ts

new revisions of this sd mux have a different identifier - so we have to update the string used to search for it so it works with both old and new

sd-mux: linux-gmbh: fix seach for device for new mux board revision

---

lib/flashing/devices/iot-gate-imx8plus-d1d8.json
lib/flashing/devices/iot-gate-imx8plus.json
lib/flashing/devices/iotdin-imx8p-d1d8.json
lib/flashing/devices/iotdin-imx8p.json
lib/flashing/index.ts

In https://github.com/balena-os/iot-gate-imx8plus-flashtools/pull/10 we removed the DRAM arg from the flashing tools, and thus need to update the autokit flashing procedure.
https://github.com/balena-io/contracts/pull/434 proposes two new IOTDIN-IMX8P device-types which share the same flashing tools and provisioning procedure with the IOT-GATE-IMX8PLUS devices, so we add their json files in this PR.

Update iot-gate-imx8plus flashing args, add iotdir-imx8p json files

---

lib/features/network/implementations/linux-device/README.md
lib/features/network/implementations/linux-device/networkManager.ts

allow for configurable wifi access point channel

---

lib/features/power/implementations/autokit-relay/README.md
lib/features/power/implementations/crelay/README.md
lib/features/power/implementations/crelay/index.ts

This allows for specifying the serial number of the crelay compatible relay being used to control power - for the case where multiple connected devices are picked up by crelay tooling (e.g an FTDI usb to serial adapter)
supersedes https://github.com/balena-io-hardware/autokit-interface-sw/pull/81 
Change-type: minor

power: crelay: clean up and enable use of multiple compatible devices

---

lib/features/sd-mux/implementations/sdwire/index.ts

The mirror we were using to clone the sd-mux-ctrl repo from was taking a long time to clone - replace it with this, which I think is functionally the same

sd-wire: use a different mirror for tooling

---

lib/flashing/index.ts

Even though armv7 can build and run on aarch64, it does not work for locked devices, but the aarch64 build does.

flashing: iot-gate:  use machine's architecture

---

lib/features/power/implementations/autokit-relay/README.md
lib/features/power/implementations/autokit-relay/device-overrides/jetson-orin-nx-xv3.ts
lib/features/power/implementations/autokit-relay/device-overrides/jetson-tx2.ts
lib/features/power/implementations/autokit-relay/index.ts
lib/features/power/index.ts
lib/flashing/devices/jetson-orin-nx-xv3.json
lib/flashing/index.ts
lib/flashing/powerDetection/ethernet.ts

This board needed a device specific power mechanism override, and a way to use a different machine name than its DT slug for the jetson flash scripts

Add jetson-orin-nx-xv3 device type

---

lib/flashing/devices/generic-emmc-container-boot-switch.json
lib/flashing/index.ts

This is to enable devices types where an "external" container is run to prepare the device before flashing

Add emmc flasher type and generic container run
