balena-os/autokit-interface-sw

- lib/flashing/devices/intel-nuc.json
- lib/flashing/index.ts
> add flasher image support

- .github/workflows/flowzone.yml
- package.json
> convert from balenaCI to flowzone

- balena.yml
> fix balena.yml

- balena.yml
> fix bold in usage in balena.yml

- balena.yml
- docker-compose.yml
> fix bolding in balena.yaml again, and fix env vars

- lib/features/sd-mux/implementations/linux-gmbh/index.ts
> fix sd mux naming

- lib/features/sd-mux/implementations/linux-gmbh/index.ts
> trim newline from sd mux name

- Dockerfile.template
resolves https://github.com/balena-io-hardware/autokit-sw/issues/27
> use arch in dockerfile to enable multi arch builds

- lib/server.ts
- package-lock.json
- package.json
Signed-off-by: Pedro Henrique Kopper <pedro.kopper@balena.io>
> Add uploadImage endpoint

- README.md
Signed-off-by: Pedro Henrique Kopper <pedro.kopper@balena.io>
> Update documentation on uploadImage

- lib/features/serial/implementations/dummy-serial/index.ts
- lib/features/serial/implementations/ftdi/index.ts
- lib/interfaces.d.ts
resolves https://github.com/balena-io-hardware/autokit-sw/issues/26
> separate serial read and write functions

- lib/features/network/implementations/dummy-network/index.ts
- lib/features/network/implementations/linux-device/index.ts
- lib/flashing/index.ts
- lib/interfaces.d.ts
> remove hard coded eth1 interface

- lib/features/sd-mux/implementations/linux-gmbh/README.md
- lib/features/sd-mux/implementations/sdwire/README.md
- lib/features/sd-mux/implementations/sdwire/index.ts
add new Sd mux to the selectable hardware https://shop.3mdeb.com/shop/open-source-hardware/sdwire/
> add sdwire mux

- lib/features/sd-mux/index.ts
> add sdwire to implementation list

- .github/workflows/flowzone.yml
Updated flowzone configuration
> Update flowzone to enable contributions

- lib/flashing/devices/jetson-orin-nano-devkit-nvme.json
- lib/flashing/index.ts
requires docker on the same host to use
> add flashing for jetson-flash devices

- lib/features/power/implementations/crelay/index.ts
- lib/features/sd-mux/implementations/sdwire/index.ts
- lib/flashing/index.ts
> move git clones from worker dockerfile to autokit init

- lib/features/sd-mux/implementations/sdwire/index.ts
> fix sdwire setup

- lib/features/digitalRelay/README.md
- lib/features/digitalRelay/implementations/usb-relay/README.md
- lib/features/keyboard/README.md
- lib/features/keyboard/implementations/rpi0-keyboard/README.md
- lib/features/network/README.md
- lib/features/network/implementations/linux-device/README.md
- lib/features/power/README.md
- lib/features/power/implementations/autokit-relay/README.md
- lib/features/power/implementations/crelay/README.md
- lib/features/sd-mux/README.md
- lib/features/serial/README.md
- lib/features/serial/implementations/ftdi/README.md
- lib/flashing/README.md
- lib/flashing/devices/generic-usb-boot.json
> Add documentation for all current inv vars and configuration vars

- lib/flashing/devices/dv-xavier-nx-nvme.json
- lib/flashing/index.ts
This PR adds a flash config json for dv-xavier-nx-nvme device type
> Add dv-xavier-nx-nvme device type

- lib/flashing/devices/jetson-orin-nano-seeed-j3010.json
> flashing/devices: Add Jetson Orin Nano 4GB Seeed json

- lib/flashing/index.ts
> add configurable delay to wait for sd mux to settle

- package-lock.json
- package.json
This is to fix builds with node 18.20.5 + python > 3.11
> Change dbus-next to 0.9.0

- lib/index.ts
> lib/index.ts: Trigger new build and release

- lib/flashing/devices/jetson-nano-emmc.json
- lib/flashing/devices/jetson-nano.json
- lib/flashing/devices/jn30b-nano.json
> flashing/devices: Add Jetson Nano eMMC and derivate device-types

- lib/flashing/index.ts
> exit cleanly after flashing iot-gate devices
